/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as rentVaultSol from "./RentVault.sol";
export { TenancyIndex__factory } from "./TenancyIndex__factory";
