/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rentVaultSol from "./RentVault.sol";
export type { rentVaultSol };
export type { TenancyIndex } from "./TenancyIndex";
