/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TenancyIndex {
  export type TenancyStruct = {
    leaseId: BigNumberish;
    landlord: AddressLike;
    tenant: AddressLike;
    leaseCID: string;
    rentAmount: BigNumberish;
    token: AddressLike;
    periodSeconds: BigNumberish;
    startDate: BigNumberish;
    endDate: BigNumberish;
    active: boolean;
  };

  export type TenancyStructOutput = [
    leaseId: bigint,
    landlord: string,
    tenant: string,
    leaseCID: string,
    rentAmount: bigint,
    token: string,
    periodSeconds: bigint,
    startDate: bigint,
    endDate: bigint,
    active: boolean
  ] & {
    leaseId: bigint;
    landlord: string;
    tenant: string;
    leaseCID: string;
    rentAmount: bigint;
    token: string;
    periodSeconds: bigint;
    startDate: bigint;
    endDate: bigint;
    active: boolean;
  };
}

export interface TenancyIndexInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeTenancy"
      | "confidentialProtocolId"
      | "fetchTenancy"
      | "listTenanciesByGuest"
      | "listTenanciesByHost"
      | "nextTenancyId"
      | "registerTenancy"
      | "reviseTenancy"
      | "tenancies"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TenancyClosed" | "TenancyRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closeTenancy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fetchTenancy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listTenanciesByGuest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listTenanciesByHost",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTenancyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerTenancy",
    values: [
      AddressLike,
      string,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "reviseTenancy",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tenancies",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "closeTenancy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchTenancy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listTenanciesByGuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listTenanciesByHost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTenancyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTenancy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviseTenancy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tenancies", data: BytesLike): Result;
}

export namespace TenancyClosedEvent {
  export type InputTuple = [leaseId: BigNumberish];
  export type OutputTuple = [leaseId: bigint];
  export interface OutputObject {
    leaseId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TenancyRegisteredEvent {
  export type InputTuple = [
    leaseId: BigNumberish,
    landlord: AddressLike,
    tenant: AddressLike
  ];
  export type OutputTuple = [leaseId: bigint, landlord: string, tenant: string];
  export interface OutputObject {
    leaseId: bigint;
    landlord: string;
    tenant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TenancyIndex extends BaseContract {
  connect(runner?: ContractRunner | null): TenancyIndex;
  waitForDeployment(): Promise<this>;

  interface: TenancyIndexInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeTenancy: TypedContractMethod<
    [leaseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  fetchTenancy: TypedContractMethod<
    [leaseId: BigNumberish],
    [TenancyIndex.TenancyStructOutput],
    "view"
  >;

  listTenanciesByGuest: TypedContractMethod<
    [tenant: AddressLike],
    [bigint[]],
    "view"
  >;

  listTenanciesByHost: TypedContractMethod<
    [landlord: AddressLike],
    [bigint[]],
    "view"
  >;

  nextTenancyId: TypedContractMethod<[], [bigint], "view">;

  registerTenancy: TypedContractMethod<
    [
      tenant: AddressLike,
      leaseCID: string,
      rentAmount: BigNumberish,
      token: AddressLike,
      periodSeconds: BigNumberish,
      startDate: BigNumberish,
      endDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  reviseTenancy: TypedContractMethod<
    [
      leaseId: BigNumberish,
      newLeaseCID: string,
      newRentAmount: BigNumberish,
      newToken: AddressLike,
      newPeriodSeconds: BigNumberish,
      newStartDate: BigNumberish,
      newEndDate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  tenancies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        leaseId: bigint;
        landlord: string;
        tenant: string;
        leaseCID: string;
        rentAmount: bigint;
        token: string;
        periodSeconds: bigint;
        startDate: bigint;
        endDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeTenancy"
  ): TypedContractMethod<[leaseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fetchTenancy"
  ): TypedContractMethod<
    [leaseId: BigNumberish],
    [TenancyIndex.TenancyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "listTenanciesByGuest"
  ): TypedContractMethod<[tenant: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "listTenanciesByHost"
  ): TypedContractMethod<[landlord: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextTenancyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerTenancy"
  ): TypedContractMethod<
    [
      tenant: AddressLike,
      leaseCID: string,
      rentAmount: BigNumberish,
      token: AddressLike,
      periodSeconds: BigNumberish,
      startDate: BigNumberish,
      endDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reviseTenancy"
  ): TypedContractMethod<
    [
      leaseId: BigNumberish,
      newLeaseCID: string,
      newRentAmount: BigNumberish,
      newToken: AddressLike,
      newPeriodSeconds: BigNumberish,
      newStartDate: BigNumberish,
      newEndDate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tenancies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        leaseId: bigint;
        landlord: string;
        tenant: string;
        leaseCID: string;
        rentAmount: bigint;
        token: string;
        periodSeconds: bigint;
        startDate: bigint;
        endDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TenancyClosed"
  ): TypedContractEvent<
    TenancyClosedEvent.InputTuple,
    TenancyClosedEvent.OutputTuple,
    TenancyClosedEvent.OutputObject
  >;
  getEvent(
    key: "TenancyRegistered"
  ): TypedContractEvent<
    TenancyRegisteredEvent.InputTuple,
    TenancyRegisteredEvent.OutputTuple,
    TenancyRegisteredEvent.OutputObject
  >;

  filters: {
    "TenancyClosed(uint256)": TypedContractEvent<
      TenancyClosedEvent.InputTuple,
      TenancyClosedEvent.OutputTuple,
      TenancyClosedEvent.OutputObject
    >;
    TenancyClosed: TypedContractEvent<
      TenancyClosedEvent.InputTuple,
      TenancyClosedEvent.OutputTuple,
      TenancyClosedEvent.OutputObject
    >;

    "TenancyRegistered(uint256,address,address)": TypedContractEvent<
      TenancyRegisteredEvent.InputTuple,
      TenancyRegisteredEvent.OutputTuple,
      TenancyRegisteredEvent.OutputObject
    >;
    TenancyRegistered: TypedContractEvent<
      TenancyRegisteredEvent.InputTuple,
      TenancyRegisteredEvent.OutputTuple,
      TenancyRegisteredEvent.OutputObject
    >;
  };
}
