/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RentVault {
  export type ReceiptStruct = {
    receiptId: BigNumberish;
    leaseId: BigNumberish;
    payer: AddressLike;
    payee: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    receiptCID: string;
    txHashRef: BytesLike;
    encryptedAmount: BytesLike;
  };

  export type ReceiptStructOutput = [
    receiptId: bigint,
    leaseId: bigint,
    payer: string,
    payee: string,
    token: string,
    amount: bigint,
    timestamp: bigint,
    receiptCID: string,
    txHashRef: string,
    encryptedAmount: string
  ] & {
    receiptId: bigint;
    leaseId: bigint;
    payer: string;
    payee: string;
    token: string;
    amount: bigint;
    timestamp: bigint;
    receiptCID: string;
    txHashRef: string;
    encryptedAmount: string;
  };
}

export interface RentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeReceipt"
      | "bypassFheVerify"
      | "confidentialProtocolId"
      | "erc20SecurityByLease"
      | "ethSecurityByLease"
      | "fetchReceiptsByTenancy"
      | "fetchReceiptsByUser"
      | "lodgeBond"
      | "lodgeBondToken"
      | "nextReceiptId"
      | "owner"
      | "receipts"
      | "receiptsByLease"
      | "receiptsByUser"
      | "registry"
      | "releaseBond"
      | "remitRent"
      | "remitRentToken"
      | "renounceOwnership"
      | "setBypassFheVerify"
      | "transferOwnership"
      | "viewEncryptedAmount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BondLodged"
      | "BondReleased"
      | "OwnershipTransferred"
      | "RentRemitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeReceipt",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bypassFheVerify",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "erc20SecurityByLease",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ethSecurityByLease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchReceiptsByTenancy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchReceiptsByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lodgeBond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lodgeBondToken",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextReceiptId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receipts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiptsByLease",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiptsByUser",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseBond",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remitRent",
    values: [BigNumberish, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "remitRentToken",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBypassFheVerify",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "viewEncryptedAmount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bypassFheVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc20SecurityByLease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethSecurityByLease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchReceiptsByTenancy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fetchReceiptsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lodgeBond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lodgeBondToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextReceiptId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiptsByLease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiptsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "remitRent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remitRentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBypassFheVerify",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewEncryptedAmount",
    data: BytesLike
  ): Result;
}

export namespace BondLodgedEvent {
  export type InputTuple = [
    leaseId: BigNumberish,
    from: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    leaseId: bigint,
    from: string,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    leaseId: bigint;
    from: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondReleasedEvent {
  export type InputTuple = [
    leaseId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    leaseId: bigint,
    to: string,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    leaseId: bigint;
    to: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RentRemittedEvent {
  export type InputTuple = [
    receiptId: BigNumberish,
    leaseId: BigNumberish,
    payer: AddressLike,
    amount: BigNumberish,
    token: AddressLike
  ];
  export type OutputTuple = [
    receiptId: bigint,
    leaseId: bigint,
    payer: string,
    amount: bigint,
    token: string
  ];
  export interface OutputObject {
    receiptId: bigint;
    leaseId: bigint;
    payer: string;
    amount: bigint;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RentVault extends BaseContract {
  connect(runner?: ContractRunner | null): RentVault;
  waitForDeployment(): Promise<this>;

  interface: RentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeReceipt: TypedContractMethod<
    [receiptId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  bypassFheVerify: TypedContractMethod<[], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  erc20SecurityByLease: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  ethSecurityByLease: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  fetchReceiptsByTenancy: TypedContractMethod<
    [leaseId: BigNumberish],
    [RentVault.ReceiptStructOutput[]],
    "view"
  >;

  fetchReceiptsByUser: TypedContractMethod<
    [user: AddressLike],
    [RentVault.ReceiptStructOutput[]],
    "view"
  >;

  lodgeBond: TypedContractMethod<[leaseId: BigNumberish], [void], "payable">;

  lodgeBondToken: TypedContractMethod<
    [leaseId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextReceiptId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  receipts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string
      ] & {
        receiptId: bigint;
        leaseId: bigint;
        payer: string;
        payee: string;
        token: string;
        amount: bigint;
        timestamp: bigint;
        receiptCID: string;
        txHashRef: string;
        encryptedAmount: string;
      }
    ],
    "view"
  >;

  receiptsByLease: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  receiptsByUser: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  releaseBond: TypedContractMethod<
    [leaseId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  remitRent: TypedContractMethod<
    [
      leaseId: BigNumberish,
      amountExt: BytesLike,
      inputProof: BytesLike,
      receiptCID: string
    ],
    [void],
    "payable"
  >;

  remitRentToken: TypedContractMethod<
    [
      leaseId: BigNumberish,
      amount: BigNumberish,
      amountExt: BytesLike,
      inputProof: BytesLike,
      receiptCID: string
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBypassFheVerify: TypedContractMethod<[v: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  viewEncryptedAmount: TypedContractMethod<
    [receiptId: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeReceipt"
  ): TypedContractMethod<
    [receiptId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bypassFheVerify"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "erc20SecurityByLease"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "ethSecurityByLease"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "fetchReceiptsByTenancy"
  ): TypedContractMethod<
    [leaseId: BigNumberish],
    [RentVault.ReceiptStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "fetchReceiptsByUser"
  ): TypedContractMethod<
    [user: AddressLike],
    [RentVault.ReceiptStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "lodgeBond"
  ): TypedContractMethod<[leaseId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "lodgeBondToken"
  ): TypedContractMethod<
    [leaseId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextReceiptId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receipts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string
      ] & {
        receiptId: bigint;
        leaseId: bigint;
        payer: string;
        payee: string;
        token: string;
        amount: bigint;
        timestamp: bigint;
        receiptCID: string;
        txHashRef: string;
        encryptedAmount: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiptsByLease"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiptsByUser"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseBond"
  ): TypedContractMethod<
    [leaseId: BigNumberish, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remitRent"
  ): TypedContractMethod<
    [
      leaseId: BigNumberish,
      amountExt: BytesLike,
      inputProof: BytesLike,
      receiptCID: string
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "remitRentToken"
  ): TypedContractMethod<
    [
      leaseId: BigNumberish,
      amount: BigNumberish,
      amountExt: BytesLike,
      inputProof: BytesLike,
      receiptCID: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBypassFheVerify"
  ): TypedContractMethod<[v: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "viewEncryptedAmount"
  ): TypedContractMethod<[receiptId: BigNumberish], [string], "view">;

  getEvent(
    key: "BondLodged"
  ): TypedContractEvent<
    BondLodgedEvent.InputTuple,
    BondLodgedEvent.OutputTuple,
    BondLodgedEvent.OutputObject
  >;
  getEvent(
    key: "BondReleased"
  ): TypedContractEvent<
    BondReleasedEvent.InputTuple,
    BondReleasedEvent.OutputTuple,
    BondReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RentRemitted"
  ): TypedContractEvent<
    RentRemittedEvent.InputTuple,
    RentRemittedEvent.OutputTuple,
    RentRemittedEvent.OutputObject
  >;

  filters: {
    "BondLodged(uint256,address,uint256,address)": TypedContractEvent<
      BondLodgedEvent.InputTuple,
      BondLodgedEvent.OutputTuple,
      BondLodgedEvent.OutputObject
    >;
    BondLodged: TypedContractEvent<
      BondLodgedEvent.InputTuple,
      BondLodgedEvent.OutputTuple,
      BondLodgedEvent.OutputObject
    >;

    "BondReleased(uint256,address,uint256,address)": TypedContractEvent<
      BondReleasedEvent.InputTuple,
      BondReleasedEvent.OutputTuple,
      BondReleasedEvent.OutputObject
    >;
    BondReleased: TypedContractEvent<
      BondReleasedEvent.InputTuple,
      BondReleasedEvent.OutputTuple,
      BondReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RentRemitted(uint256,uint256,address,uint256,address)": TypedContractEvent<
      RentRemittedEvent.InputTuple,
      RentRemittedEvent.OutputTuple,
      RentRemittedEvent.OutputObject
    >;
    RentRemitted: TypedContractEvent<
      RentRemittedEvent.InputTuple,
      RentRemittedEvent.OutputTuple,
      RentRemittedEvent.OutputObject
    >;
  };
}
