/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITenancyIndex__factory } from "./ITenancyIndex__factory";
export { RentVault__factory } from "./RentVault__factory";
